version: "3.3"

services:
  core:
    image: quay.io/blockstack/bitcoind:latest
    restart: always
    volumes:
      - "/bitcoind/configs/bitcoin/bitcoin.conf:/etc/bitcoin/bitcoin.conf"
      - "/data/bitcoin:/root/.bitcoin"
    ports:
      - "38332:8332"
      - "38333:8333"
      - "58333:28332"
    expose:
      - 38332
      - 38333
      - 58332
    environment:
      BTC_CONF: "/etc/bitcoin/bitcoin.conf"
      BTC_DATA: "/root/.bitcoin"
      BTC_PID: "/run/bitcoind/bitcoind.pid"
    networks:
      - bitcoin

  haproxy:
    image: haproxy:alpine
    restart: always
    depends_on:
      - core
    volumes:
      - "/bitcoind/configs/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - "8332:8332"
      - "8333:8333"
      - "1024:1024"
    expose:
      - 8332
      - 8333
      - 1024
    environment:
      - HOST=${HOSTNAME}
    command: /usr/local/sbin/haproxy -f /usr/local/etc/haproxy/haproxy.cfg -L $HOST
    networks:
      - bitcoin

  # python:
  #   image: quay.io/blockstack/bitcoind:python.gcp
  #   depends_on:
  #     - haproxy
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #     - "/bitcoind/configs/haproxy:/bitcoind/configs/haproxy"
  #     - "/bitcoind/templates:/bitcoind/templates"
  #   environment:
  #     PROJECT: "ops-shared"
  #     ROLE: "bitcoind"
  #   networks:
  #     - bitcoind

networks:
  bitcoin:
    driver: bridge
