name: bitcoin-alpine-multistage
env:
  QUAY_IMAGE: quay.io/blockstack/bitcoind
  DOCKERHUB_IMAGE: blockstack/bitcoind
  CONTEXT: Dockerfiles/bitcoin
  DOCKERFILE: Dockerfiles/bitcoin/Dockerfile.alpine.multistage

on:
  push:
    paths:
      - Dockerfiles/bitcoin/**
      - .github/workflows/bitcoin-alpine-multistage.yml
  pull_request:
    paths:
      - Dockerfiles/bitcoin/**
      - .github/workflows/bitcoin-alpine-multistage.yml

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get release version
        id: get_version
        run: echo "RELEASE_VERSION=$(cat ${CONTEXT}/VERSION)" >> $GITHUB_ENV

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ${{ env.DOCKERFILE }}
          context: ${{ env.CONTEXT }}
          build-args: BTC_VERSION=${{ env.RELEASE_VERSION }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            ${{ env.QUAY_IMAGE }}:${{ env.RELEASE_VERSION }}
            blockstack/bitcoind:${{ env.RELEASE_VERSION }}
