name: bitcoin-alpine
env:
  QUAY_IMAGE: quay.io/blockstack/bitcoind
  DOCKERHUB_IMAGE: blockstack/bitcoind
  CONTEXT: Dockerfiles/bitcoin
  BINARY_DOCKERFILE: Dockerfiles/bitcoin/Dockerfile.alpine.binary
  DOCKERFILE: Dockerfiles/bitcoin/Dockerfile.alpine


on:
  push:
    paths:
      - Dockerfiles/bitcoin/Dockerfile.alpine.binary
      - Dockerfiles/bitcoin/Dockerfile.alpine
      - Dockerfiles/bitcoin/make_binary_dist.sh
      - Dockerfiles/bitcoin/VERSION
      - .github/workflows/bitcoin-alpine.yml
  pull_request:
    paths:
      - Dockerfiles/bitcoin/Dockerfile.alpine.binary
      - Dockerfiles/bitcoin/Dockerfile.alpine
      - Dockerfiles/bitcoin/make_binary_dist.sh
      - Dockerfiles/bitcoin/VERSION
      - .github/workflows/bitcoin-alpine.yml

jobs:
  setup:
    name: Setup Action
    runs-on: ubuntu-latest
    outputs:
      btc_version: ${{ steps.version.outputs.release_version }}
    steps:
      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          # driver: docker
          driver-opts: network=host

      - name: Retrieve BTC Version
        id: get_version
        run: echo "RELEASE_VERSION=$(cat ${CONTEXT}/VERSION)" >> $GITHUB_ENV

      - name: Output BTC Version
        id: version
        run: echo "::set-output name=release_version::${{ env.RELEASE_VERSION }}"

# - run: echo ${{needs.setup.outputs.btc_version}} ${{needs.job1.outputs.output2}}

  build-binary:
    name: Bitcoin Core Binary Build
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      # fail-fast: true
      matrix:
        build: ["", "-statoshi"]
        # build: ["", "-norpc", "-statoshi"]
    steps:

      # - name: Build BTC Binary Archive
      #   uses: docker/build-push-action@v2
      #   with:
      #     load: true
      #     file: ${{ env.BINARY_DOCKERFILE }}
      #     context: ${{ env.CONTEXT }}
      #     tags: ${{ env.QUAY_IMAGE }}:${{ env.RELEASE_VERSION }}
      #     build-args: |
      #       BTC_VERSION=${{ env.RELEASE_VERSION }}
      #       BTC_BUILD=${{ matrix.build }}
      #     push: false
      #
      # - name: Copy BTC Binary Archive
      #   shell: bash
      #   run: |
      #     docker rm -f bitcoin-binary || true
      #     docker create --name bitcoin-binary ${{ env.QUAY_IMAGE }}:${{ env.RELEASE_VERSION }}
      #     docker cp bitcoin-binary:/srv/build build
      #     docker rm -f bitcoin-binary
      #
      # - name: Upload BTC Binary Artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: bitcoin-${{ env.RELEASE_VERSION }}.tar.gz
      #     path: |
      #       build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Bitcoin Core - ${{needs.setup.outputs.btc_version}}
          tag_name: ${{needs.setup.outputs.btc_version}}
          files: build/*.tar.gz
          # body_path: ${{ github.workflow }}-CHANGELOG.txt
          # body: |
          #   Alpine Bitcoin Binaries for version: ${{ env.RELEASE_VERSION }}
          #   - statoshi fork: https://github.com/jlopp/statoshi
          #   - btc main: https://github.com/bitcoin/bitcoin
          #   - btc main (without wallet or some rpc commands): https://github.com/bitcoin/bitcoin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-image:
    name: Build Docker Image
    needs: setup, build-binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # fail-fast: true
        build: ["", "-statoshi"]
        # build: ["", "-norpc", "-statoshi"]
    steps:
      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          file: ${{ env.DOCKERFILE }}
          context: ${{ env.CONTEXT }}
          build-args: |
            BTC_VERSION=${{needs.setup.outputs.btc_version}}
            BTC_BUILD=${{ matrix.build }}
          push: true
          tags: |
            ${{ env.QUAY_IMAGE }}:${{needs.setup.outputs.btc_version}}${{ matrix.build }}
            ${{ env.DOCKERHUB_IMAGE }}:${{needs.setup.outputs.btc_version}}${{ matrix.build }}
